spring:
  application:
    name: code
  
  # MySQL Setup
  datasource:
    url: jdbc:mysql://labs-mysql-large-damaged-architect.mysql.databases.labs.skills.network:3306/store
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  
  # Setup JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true